# spring application name
spring:
  application:
   name: ImgurApp

---
# HSQLDB Configuration
spring:
  datasource:
    url: jdbc:hsqldb:mem:imageapp
    username: username
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20 # keeping it to default 20

---
# Hibernate configuration
spring:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect

---
# for imgur image upload functionality
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
# adding cache manager for faster retrieval
spring:
  cache:
    type: caffeine
    cache-names: imgurCache, userCache, imgurDownloadCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

---
# for Kafka configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: imgur-app-clients
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# for IMGUR
imgur:
  client-id: 6bb41ee57a70323
  kafka-topic: imgur-events


